### ISSUE TITLE
Crash quand appui sur Shift

### ISSUE THREAD

**Issue by Mizugola** [Loodoor/UrWorld-Alpha-3.x#3]
Lorsqu'on appuie sur Shift dans le menu, le jeu crashe.

**Comment by Loodoor** [comment]
oui, ce bug est connu, pourtant la touche est bien mise en interdite, donc je ne suis pas censé la traiter dans la texte box :/

**Comment by Loodoor** [comment]
bug fixé, simple oublie dans le code d'exclure K_LSHIFT des lettres >.<'
mea culpa
